katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create_task/', create_task, name='create_task'),
    path('change-status/<int:id>', status, name='status'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('json/',show_json_todolist,name='show_json_todolist'),
    path('show/json/',show_todolist_ajax,name='show_todolist_ajax'),
    path('add/',todolist_add,name='todolist_add')
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default= False)

todolist/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    description = forms.CharField(label ='Description',widget= forms.Textarea, required=False)

todolist/views.py
from django.shortcuts import HttpResponse, render
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from todolist.models import Task
from todolist.forms import TaskForm
from django.contrib import messages
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.


# fungsi to do list
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        'username' : request.user.username,
        'list_task' : data_task,
    }
    return render(request, "todolist.html", context)


# fungsi registrasi
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


# fungsi login
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
            response.set_cookie('last_login', str(datetime.datetime.now())) 
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

# fungsi log out
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

# fungsi create task
@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TaskForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            Task.objects.create(
            user = request.user,
            date = datetime.datetime.today(),
            title = form.cleaned_data['title'],
            description = form.cleaned_data['description'],
            is_finished = False,
                )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    else:
        context = {'form': form,
    } 
    
    return render(request, 'create_task.html', context)                

# fungsi delete task
def delete_task(request, id):
    task = Task.objects.get(user=request.user, pk=id)
    task.delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

# fungsi status
def status(request,id):
    status_data = Task.objects.get(pk=id)
    if status_data.is_finished:
       status_data.is_finished = False
    else:
        status_data.is_finished = True
    status_data.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
def show_json_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data_task), content_type="application/json")

def show_todolist_ajax(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        'username' : request.user.username,
        'list_task' : data_task,

    }
    return render(request, "todolist_ajax.html", context)
    
@csrf_exempt
def todolist_add(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.date.today()
        user = request.user
        todo = Task.objects.create(title=title, description=description, date=date, user=user)

        result = {
            'fields':{
                'title':todo.title,
                'description':todo.description,
                'date':todo.date,
            },
            'pk':todo.pk
        }
        return JsonResponse(result)

todolist/templates/create_task.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create Task</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/log-reg-create.css' %}">

  </head>
  <body>

    <div class="creation">

      <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
      </div>

      <form method="POST" action="">
        {% csrf_token %}

        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Title" class="form-control">

        <label for="description">Description</label>
        <input type="text" name="description" placeholder="Description" class="form-control">

        <button type="submit" value="Submit">Submit</button>
        <a href="{% url 'todolist:show_todolist' %}">Back</a>
      </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/log-reg-create.css' %}">
    
  </head>
  <body>

    <div class="login">

      <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
      </div>
      
      <form method="POST" action="">
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" class="form-control">

        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Password" class="form-control">
        
        <button type="submit" value="Login">Log In</button>

        <a href="{% url 'todolist:register' %}">No Account? Register now!</a>

        {% if messages %}
          <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}   
      </form>      
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/log-reg-create.css' %}">
    
  </head>
  <body>

    <div class="register">

      <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
      </div>
    
      <form method="POST" >  
        {% csrf_token %}  

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" class="form-control" required>

        <label for="password">Password (8 letters minimum!)</label>
        <input type="password" name="password1" placeholder="Password" class="form-control" required>

        <label for="password">Password Confirmation</label>
        <input type="password" name="password2" placeholder="Password" class="form-control" required>

        <button type="submit" name = "submit" value="Register">Register</button>
        
        <a href="{% url 'todolist:login' %}">Back</a>

        {% if messages %}  
          <ul>   
            {% for message in messages %}  
              <li>{{ message }}</li>  
            {% endfor %}  
          </ul>   
        {% endif %}

      </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock content %}

todolist/templates/todolist.html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To do List!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
      body  {
        background: linear-gradient(130deg, #1a2a6c, #b21f1f 41.07%, #fdbb2d 76.05%);
        font-family: sans-serif;
      }
  </style>
    
  </head>

  <nav class="navbar navbar-dark" style="background-color: #b21f1f;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{nama}}</a>
     
          <!--<button class="btn btn-outline-success" type="submit">Logout</button>-->
          <button><a href="{% url 'todolist:logout' %}">Logout</a></button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <h1>Your Todolist!</h1>
  </div>
  

  <!-- <table>
    <tr>
      <th class ="header">Tanggal Pembuatan Task</th>
      <th class ="header">Judul Task</th>
      <th class ="header">Deskripsi Task</th>
      <th class ="header">Status</th>
      <th class ="header">Delete</th>
    </tr> -->
    
    {% comment %} Add the data below this line {% endcomment %}
    {% for Task in list_task %}

    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{Task.title}}</h5>
        <p class="card-text">{{Task.description}}</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{Task.date}}</li>
      </ul>
      <div class="card-body">
        {% if Task.is_finished  %}
          <a href="{% url 'todolist:status' Task.id %}" class="card-link">Selesai</a>
        {% else %}
          <a href="{% url 'todolist:status' Task.id %}" class="card-link">Belum Selesai</a>
        {% endif %}
        <a href="{% url 'todolist:delete_task' Task.id %}" class="btn btn-danger btn-sm" role="button">Delete Task</a>
        
      </div>
    </div>
    
    <!-- <tr>
        <th>{{task.date}}</th>
        <th>{{task.title}}</th>
        <th>{{task.description}}</th>
        {% if task.is_finished  %}
          <th><a href="update_task/{{task.pk}}">selesai</a></th>
        {% else %}
          <th><a href="update_task/{{task.pk}}">belum selesai</a></th>
        {% endif %}
        <th><a href="delete_task/{{task.pk}}">Delete Task</a></th>        
    </tr> -->
  {% endfor %}
  <!-- </table> -->
  <button><a href="{% url 'todolist:create_task' %}">Add task</a></button>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Create Task</button>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">New Task For You</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Task:</label>
              <input type="text" class="form-control" id="#title_field">
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Description:</label>
              <textarea class="form-control" id="#description_field"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary"id="pesan" data-bs-dismiss="modal">Add</button>
        </div>
      </div>
    </div>
  </div>
</html>

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block content %}

<head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    $.get("http://localhost:8000/todolist/json", function(data) {
     for (i=0;i<data.length;i++){
        $(".card").append(
            `<div class="card-part">
            <h5 class="card-title">${data[i].fields.title}</h5>
            <p class="card-text">${data[i].fields.date}</p>
            <p class="card-description">${data[i].fields.description}</p>
          </div>`)
      }
    })
    $("#pesan").click(function(){
    event.preventDefault();
    $.post("/todolist/add/",{
        title : $('#title_field').val(),
        description : $('#description_field').val()},
        function (result) {
            $('.card').append(`<div class="card-part" >
                <h5 class="card-title">${result.fields.title}</h5>
                <p class="card-text">${result.fields.date}</p>
                <p class="card-description">${result.fields.description}</p>
                </div>`)
            $('#title_field').val(''),
            $('#description_field').val('')
        })
    })
  })

</script>
</head>
<style>
    body {
        display: flex;
        margin:auto;
        background: linear-gradient(#9F98E8, #aff6cf);
        font-family:Arial, Helvetica, sans-serif;
        text-align: center;
        justify-content: center;
        display: grid;
        grid-template-columns: 1fr;
        grid-template-rows: auto;
        grid-gap: 20px;
        max-width: 100%;
    }
    .card{
      background: linear-gradient(#9F98E8, #aff6cf);
      justify-content: center;
      width: 100%;
    }
    .card-part{
    background: linear-gradient(#9F98E8, #aff6cf);
    text-align: center;
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: auto;
    grid-gap: 20px;
    width: 90%;
    margin: 1rem;
    padding-bottom: 1rem;
    text-align: center;
    border: solid 2px #fcad02;
    border-radius: 10px;
    box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
    max-width:100%;
    }
    .card-title h1{
    margin:0px;
    color:#4C4C4C;
    font-size:23px;
    padding: 15px 0px 8px 0px;
    }
    .card-text p{
    min-height:10px;
    overflow: hidden;
    /* color:#848484; */
    margin:0px;
    text-align: justify;
    }
    .card-description a{
    border-radius:0px;
    font-size: 11px;
    }
</style>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"style="text-align:endblock">
    Add Task
  </button>
  <div class="card" style="width: 18rem;" id="todolist">
    <div class="container">
    </div>
  </div>  
    <!-- </table> -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">New Task For You</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Task:</label>
                <input type="text" class="form-control" id="title_field">
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Description:</label>
                <textarea class="form-control" id="description_field"></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="pesan" data-bs-dismiss="modal">Add</button>
          </div>
        </div>
      </div>
    </div>
  </table>
</form>
<br>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button>
<button ><a href="{% url 'todolist:create_task' %}">Create Task</a></button>

{% endblock content %}